#!/bin/bash

CURRENTDATE=`date +"%d-%m-%Y"`

write_lastcommand () {
	truncate -s 0 ${1:1}
	echo "backup ${1} ${2} ${3} ${4}" > ~/Dokumente/BASHSCRIPTS/lastcommand
}
archive_f () {
  tar -czf ${1} ${2}
  return
}
test_for_directory () {
	echo ${1}
	if [[ -d ${1} ]]; 
	then echo "file/directory found" ; 
	else 
		echo "Couldnt find file/directory"
		exit 1
	fi
}

if [ ${1} ==  ];
then 
	eval $(head -n 1 lastcommand)
	exit 0
fi

if [ ${1} == -help ];
then
	echo " backup [command] outputdirectory/filename inputfile/inputdirectory"
	echo ""
	echo " -din 									Default input File/Folder"
	echo " -sdin [inputfile/inputdirectory]			Set default input File/Folder"
	echo " -dout									Default output"
	echo " -sdout [outputdirectory/filename]		Set default output"
	echo ""
	echo " Commands"
	echo " -d [output] [input]					Add current date to filename"
	echo " -help								For help"
	echo ""

	line=$(head -n 1 temp.txt)
	
	echo $line
	
	exit 0
fi

if [ ${1} == -dout ] || [ ${1} == -din ]; 
then 
	test_for_file ${2}
	truncate -s 0 ~/Dokumente/BASHSCRIPTS/${1:1}
	echo "$2" > ${1:1}
	echo Succesfully
	exit 0
fi

if [ ${1} == -d ];
then
	if [ ${3} == -din ]; then in=$(head -n 1 din); else in=${3}; fi
	if [ ${2} == -dout ]; then out="$(head -n 1 dout)/${CURRENTDATE}"; else out="${2}/${CURRENTDATE}"; fi
	echo "${in}"
	echo "${out}" 
	archive_f ${out} ${in}
	write_lastcommand ${1} ${2} ${3} 
	exit 0
fi

echo error

exit 1
